name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: cd into directory
      run: cd HelloToast
    - name: Grant execute permission for gradlew
      run: chmod +x HelloToast/gradlew
    - name: currentdir
      run: pwd
    - name: Build with Gradle
      run: HelloToast/./gradlew build
